### ISSUE TITLE
DTLS Support

### ISSUE THREAD

**Issue by andre77** [dorkbox/UDT#1]
Is there a way to however use the UDT library in combination with DTLS ?

**Comment by dorkbox** [comment]
DTLS is a streaming protocol (from what I can gather on the wikipedia entry) as is UDT - but each do it in their own way. It might be possible to cobble stuff together, but I'm not the author of UDT, and I would be wary to modify their code in such a significant way.

However, it's not too difficult to layer security on top of UDT. (ie: negotiate an AES key over ECDH or something, then encrypt/decrypt the packets). I've got a java networking stack I'm preparing for release (once my executor is finished), that does exactly this, and is based on Netty and Kryo (with much inspiration/ideas/code from KryoNet. Props to Nate Sweet for fantastic work)

However, if you've got something for the UDT C++ project (this is just a fork + enhancements), I can look at pulling those changes in to the java wrapper.
