### ISSUE TITLE
mismatched delete fix

### ISSUE THREAD

**Issue by user1095108** [dorkbox/UDT#2]
change line 202 of core.cpp from
`delete m_pPeerAddr;`
to
`(AF_INET == m_iIPversion) ? delete (sockaddr_in*)m_pPeerAddr : delete (sockaddr_in6*)m_pPeerAddr;`

**Comment by dorkbox** [comment]
Ah, I see. Fixed, and thanks for reporting!

**Comment by user1095108** [comment]
A better way to fix this would be to use sockaddr_storage, if you should feel to make a more canonical fix.

**Comment by user1095108** [comment]
or just plain malloc/free

**Comment by dorkbox** [comment]
Unfortunately, I'm not very well versed with how to use `sockaddr_storage`... :/  I'd be happy to take a fix/patch/pull request for this though (whatever is easiest for you).

**Comment by user1095108** [comment]
sockaddr_storage just takes up the maximum an address can take. It is wasteful to use it in this case, but more "correct" and malloc()/free() don't require you to specify a type. The fix as it is is OK, I was just giving you ideas.

**Comment by dorkbox** [comment]
Ah, ok.

Thanks again for the fix though!
